import type { Node, Edge } from '@xyflow/react'

/** A task attached to an agent (shown in the inspector panel). */
export interface AgentTask {
  id: string
  title: string
  status: string
  progress: number
  priority: string
  repos: string[]
  /** Epoch ms of the task's last update — used server-side for ordering. */
  lastUpdatedMs?: number
}

/* React Flow v12 requires node data to be a string-indexable record, hence the
 * index signature on each data type below. */

export interface RootData {
  label: string
  workingCount: number
  agentCount: number
  repoCount: number
  [key: string]: unknown
}

export interface AgentData {
  label: string
  status: 'Working' | 'Idle'
  working: boolean
  currentTask?: string
  lastUpdate?: string
  assignedProject?: string
  activeCwd?: string | null
  repoCount: number
  taskCount: number
  tasks: AgentTask[]
  [key: string]: unknown
}

export interface ProjectData {
  label: string
  emoji?: string
  root?: string
  repoCount: number
  [key: string]: unknown
}

export interface RepoData {
  label: string
  working: boolean
  owners: string[]
  /** Id of the project node containing this repo, if any. */
  project?: string | null
  [key: string]: unknown
}

export type RootNode = Node<RootData, 'root'>
export type ProjectNode = Node<ProjectData, 'project'>
export type AgentNode = Node<AgentData, 'agent'>
export type RepoNode = Node<RepoData, 'repo'>

/** Union of every node kind the graph can contain. */
export type NetworkNode = RootNode | ProjectNode | AgentNode | RepoNode
export type NetworkEdge = Edge

/** Raw activity event as generated by the collector (metrics/activity.json). */
export interface ActivityEvent {
  id: string
  type: string
  title: string
  description: string
  timestamp: string
  icon: string
}

/** Client-side feed item — stamped with local arrival time for a real clock. */
export interface FeedItem {
  key: string
  type: string
  title: string
  description: string
  icon: string
  at: number // epoch ms when first seen on the client
}

/** WebSocket / initial-fetch payload shape. */
export interface NetworkPayload {
  type: 'agent-network:update'
  timestamp: string
  nodes: NetworkNode[]
  edges: NetworkEdge[]
  activity: ActivityEvent[]
}
